export const AVAILABLE_PROGRAMS = [
  "Honours Computer Science (BSc)",
  "Software Engineering (BASc)",
  "Computer Engineering (BASc)",
  "Electrical Engineering (BASc)",
  "Mechanical Engineering (BASc)",
  "Civil Engineering (BASc)",
  "Mathematics (BSc)",
  "Statistics (BSc)",
  "Data Science (BSc)",
  "Business Technology Management (BCom)",
  "Finance (BCom)",
  "Accounting (BCom)",
  "Marketing (BCom)",
  "Economics (BA)",
  "Health Sciences (BHSc)",
  "Biology (BSc)",
  "Biochemistry (BSc)",
  "Psychology (BA/BSc)",
  "Sociology (BA)",
  "Digital Journalism (BJour)",
  "Communication (BA)",
  "Design (BDes)",
  "Human Kinetics (BHK)"
];
